export const mock_products = [{
    "id": 1,
    "bar_code": 68,
    "category": "Outros",
    "date": "2021-12-08",
    "description": "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    "height": 40,
    "length": 39,
    "name": "Lotstring",
    "value": 4,
    "weight": 32,
    "width": 15,
    'product_image': "https://picsum.photos/200/300",
  }, {
    "id": 2,
    "bar_code": 110,
    "category": "Roupas",
    "date": "2021-11-08",
    "description": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    "height": 88,
    "length": 39,
    "name": "Aerified",
    "value": 71,
    "weight": 65,
    "width": 54,
    'product_image': "https://picsum.photos/200/300",
  }, {
    "id": 3,
    "bar_code": 99,
    "category": "Acessório",
    "date": "2020-12-08",
    "description": "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    "height": 55,
    "length": 81,
    "name": "Subin",
    "value": 75,
    "weight": 79,
    "width": 9,
    'product_image': "https://picsum.photos/200/300",
  }];

  export const mock_categories = ['', 'Outros','Informática','Acessório','Roupas','Eletrodoméstico'];
